# Generated by Django 5.1.3 on 2024-11-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_collection_findings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="findings",
        ),
        migrations.AddField(
            model_name="finding",
            name="collections",
            field=models.ManyToManyField(
                blank=True, related_name="findings", to="catalog.collection"
            ),
        ),
    ]
