# Generated by Django 5.1.3 on 2024-11-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_collection_options_alter_feedback_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
