# Generated by Django 5.1.3 on 2024-11-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_feedback_created_at_alter_finding_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="detector_model",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
